"""
app.py — FastAPI server for CustomerSupportEnv on Hugging Face Spaces.

Endpoints (per OpenEnv deployment spec):
  GET  /               → environment info / 200 OK
  WS   /ws             → WebSocket persistent session (primary client endpoint)
  GET  /health         → {"status": "healthy"}
  GET  /docs           → OpenAPI docs (auto-generated by FastAPI)
  GET  /web            → Interactive web UI redirect → /docs
  POST /reset          → reset(task_id) → Observation JSON
  POST /step           → step(action)   → StepResult JSON
  GET  /state          → state()        → EnvState JSON
  GET  /tasks          → list all task IDs and metadata

Designed to run on HF Spaces with:
  uvicorn app:app --host 0.0.0.0 --port 7860
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, Optional
from fastapi import Body, WebSocket, WebSocketDisconnect

from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse, RedirectResponse
from pydantic import BaseModel

from env import CustomerSupportEnv
from models import Action, TaskId, ToolName
from tasks.definitions import TASK_REGISTRY

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="CustomerSupportEnv",
    description=(
        "OpenEnv-compliant customer support environment. "
        "AI agents resolve multi-step tickets using tools: "
        "order lookup, refunds, billing disputes, escalations."
    ),
    version="1.0.0",
)

# ---------------------------------------------------------------------------
# Global env instance for stateless HTTP endpoints
# (WebSocket sessions each carry their own env instance)
# ---------------------------------------------------------------------------

_env: Optional[CustomerSupportEnv] = None


def _get_env() -> CustomerSupportEnv:
    if _env is None:
        raise HTTPException(
            status_code=400,
            detail="Environment not initialised. Call /reset first.",
        )
    return _env


# ---------------------------------------------------------------------------
# Request/Response schemas
# ---------------------------------------------------------------------------

class ResetRequest(BaseModel):
    task_id: str = "order_refund"


class StepRequest(BaseModel):
    tool:    str
    params:  Dict[str, Any] = {}
    message: Optional[str] = None


# ---------------------------------------------------------------------------
# HTTP Routes
# ---------------------------------------------------------------------------

@app.get("/")
async def root():
    """Environment info — returns 200."""
    return {
        "status":      "healthy",
        "environment": "CustomerSupportEnv",
        "version":     "1.0.0",
        "tasks":       [t.value for t in TaskId],
        "endpoints":   ["/ws", "/reset", "/step", "/state", "/tasks", "/health", "/web", "/docs"],
    }


@app.get("/health")
async def health():
    """Health check — returns {"status": "healthy"} per OpenEnv spec."""
    return {"status": "healthy"}


@app.get("/web")
async def web():
    """Interactive web UI — redirects to auto-generated OpenAPI docs."""
    return RedirectResponse(url="/docs")


@app.get("/tasks")
async def list_tasks():
    """Return all task IDs with metadata."""
    result = []
    for task_id, cfg in TASK_REGISTRY.items():
        result.append({
            "task_id":         task_id.value,
            "difficulty":      cfg.difficulty,
            "description":     cfg.description,
            "max_steps":       cfg.max_steps,
            "optimal_steps":   cfg.optimal_steps,
            "sla_seconds":     cfg.sla_seconds,
            "available_tools": cfg.available_tools,
            "ticket_subject":  cfg.ticket.subject,
        })
    return result


@app.post("/reset")
async def reset(request: Optional[ResetRequest] = Body(default=None)):
    """
    Initialise (or reinitialise) the environment for a given task.
    Returns the initial Observation.
    """
    global _env

    if request is None or request.task_id is None:
        task_id = TaskId("order_refund")
    else:
        try:
            task_id = TaskId(request.task_id)
        except ValueError:
            valid = [t.value for t in TaskId]
            raise HTTPException(
                status_code=422,
                detail=f"Unknown task_id '{request.task_id}'. Valid: {valid}",
            )

    _env = CustomerSupportEnv(task_id=task_id)
    obs = _env.reset()
    return obs.model_dump()


@app.post("/step")
async def step(request: StepRequest):
    """
    Execute one action in the environment.
    Returns StepResult (observation, reward, done, info).
    """
    env = _get_env()

    try:
        tool = ToolName(request.tool)
    except ValueError:
        valid = [t.value for t in ToolName]
        raise HTTPException(
            status_code=422,
            detail=f"Unknown tool '{request.tool}'. Valid: {valid}",
        )

    action = Action(
        tool    = tool,
        params  = request.params,
        message = request.message,
    )

    try:
        result = env.step(action)
    except RuntimeError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    return result.model_dump()


@app.get("/state")
async def state():
    """Return a full snapshot of the current environment state."""
    env = _get_env()
    return env.state().model_dump()


# ---------------------------------------------------------------------------
# WebSocket /ws — Persistent session (primary OpenEnv client endpoint)
#
# Protocol (JSON messages):
#   Client → Server:
#     {"action": "reset", "task_id": "order_refund"}
#     {"action": "step",  "tool": "lookup_order", "params": {...}, "message": null}
#     {"action": "state"}
#     {"action": "ping"}
#
#   Server → Client:
#     reset  → Observation JSON
#     step   → StepResult JSON
#     state  → EnvState JSON
#     ping   → {"status": "healthy"}
#     error  → {"error": "..."}
# ---------------------------------------------------------------------------

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """
    Persistent WebSocket session.
    Each connection gets its own isolated env instance.
    """
    await websocket.accept()
    session_env: Optional[CustomerSupportEnv] = None

    try:
        while True:
            raw = await websocket.receive_text()
            try:
                msg = json.loads(raw)
            except json.JSONDecodeError:
                await websocket.send_text(json.dumps({"error": "Invalid JSON"}))
                continue

            action_type = msg.get("action", "")

            # ---- ping -------------------------------------------------------
            if action_type == "ping":
                await websocket.send_text(json.dumps({"status": "healthy"}))

            # ---- reset -------------------------------------------------------
            elif action_type == "reset":
                task_id_str = msg.get("task_id", "order_refund")
                try:
                    task_id = TaskId(task_id_str)
                except ValueError:
                    valid = [t.value for t in TaskId]
                    await websocket.send_text(json.dumps(
                        {"error": f"Unknown task_id '{task_id_str}'. Valid: {valid}"}
                    ))
                    continue
                session_env = CustomerSupportEnv(task_id=task_id)
                obs = session_env.reset()
                await websocket.send_text(json.dumps(obs.model_dump(), default=str))

            # ---- step --------------------------------------------------------
            elif action_type == "step":
                if session_env is None:
                    await websocket.send_text(json.dumps(
                        {"error": "Session not initialised. Send {\"action\": \"reset\"} first."}
                    ))
                    continue
                tool_name = msg.get("tool", "")
                params    = msg.get("params", {})
                message   = msg.get("message", None)
                try:
                    tool = ToolName(tool_name)
                except ValueError:
                    valid = [t.value for t in ToolName]
                    await websocket.send_text(json.dumps(
                        {"error": f"Unknown tool '{tool_name}'. Valid: {valid}"}
                    ))
                    continue
                step_action = Action(tool=tool, params=params, message=message)
                try:
                    result = session_env.step(step_action)
                except RuntimeError as exc:
                    await websocket.send_text(json.dumps({"error": str(exc)}))
                    continue
                await websocket.send_text(json.dumps(result.model_dump(), default=str))

            # ---- state -------------------------------------------------------
            elif action_type == "state":
                if session_env is None:
                    await websocket.send_text(json.dumps(
                        {"error": "Session not initialised. Send {\"action\": \"reset\"} first."}
                    ))
                    continue
                await websocket.send_text(
                    json.dumps(session_env.state().model_dump(), default=str)
                )

            else:
                await websocket.send_text(json.dumps(
                    {"error": f"Unknown action '{action_type}'. Use: reset, step, state, ping"}
                ))

    except WebSocketDisconnect:
        pass  # Client disconnected cleanly
    except Exception:
        pass  # Session ends on any unhandled error


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 7860))
    uvicorn.run("app:app", host="0.0.0.0", port=port, reload=False)